version: '3'
services:
    Container_A:
        image: nginx:st5
        ports:
            - "8080:80"
        volumes:
            - ./container_a/index.html:/usr/share/nginx/html/index.html
        restart: always
    Container_B:
        image: nginx:st5.1
        ports:
            - "9090:80"
        volumes:
            - ./container_b/index.html:/usr/share/nginx/html/index.html
        restart: always